### ISSUE TITLE
Typo in output warning

### ISSUE THREAD

**Issue by scriptease** [m-kraus/check_curly#1]
Hello,

There are some typos in the spelling of critical you might want to fix.

- Florian

    $Msg.='CRIITCAL Page time '.$total_time.'s exceeded time limit '.$Tc.'s';
    $Msg.='CIRITCAL String '.$Grep.' not found';

**Comment by m-kraus** [comment]
Fixed with e7a0ba8

**Comment by m-kraus** [comment]
Thanks for the hint.
