### ISSUE TITLE
check_nsc_web ;)

### ISSUE THREAD

**Issue by erSitzt** [m-kraus/check_curly#5]
@m-kraus  etwas über umwege :)

Da das Consol repository ein fork von deinem repo ist, kann man dort keine issues aufmachen.. nur mal für die zukunft ;)

**Comment by m-kraus** [comment]
@erSitzt Das war mir nicht klar (wieder was gelernt...) - ich habe gestern Abend noch Gerhard deswegen angeschrieben: er hat Issues jetzt auch für das Consol-Repo aktiviert :-)

**Comment by erSitzt** [comment]
@m-kraus  Danke dir !
Lustigerweise hatte die Google Suche nach check_nsc_web auch erstmal nur dein Repo gelistet.. evtl auch weil die anderen nur Forks sind..
